apiVersion: vendir.k14s.io/v1alpha1
kind: Config
minimumRequiredVersion: 0.12.0
directories:
- path: 01-helm-install/charts
  contents:
  - path: .
    git:
      url: https://github.com/paulbouwer/hello-kubernetes.git
      ref: v1.10.1
    includePaths:
    - deploy/helm/hello-kubernetes/**
    newRootPath: deploy/helm
- path: 04-ytt-helm-template/charts
  contents:
  - path: .
    git:
      url: https://github.com/paulbouwer/hello-kubernetes.git
      ref: v1.10.1
    includePaths:
    - deploy/helm/hello-kubernetes/**
    newRootPath: deploy/helm
- path: 05-kapp-deploy/config
  contents:
  - path: .
    directory:
      path: 02-ytt-replicas
    includePaths:
    - app.yaml
