apiVersion: v1
kind: Secret
metadata:
  name: hello-kubernetes-values
  namespace: default
  annotations:
    kapp.k14s.io/change-group: "hello-kubernetes/app"
    kapp.k14s.io/change-rule.create-order: "upsert after upserting hello-kubernetes/rbac"
    kapp.k14s.io/change-rule.delete-order: "delete before deleting hello-kubernetes/rbac"
type: Opaque
stringData:
  data.yml: |
    ingress:
      configured: true
      pathPrefix: ""
    deployment:
      container:
        image:
          repository: ghcr.io/alexandreroman/hello-kubernetes
          tag: "1.10"
    service:
      type: ClusterIP
    env:
      name: dev
      domain: gitops.dev.corp
