apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: hello-kubernetes
  namespace: default
  annotations:
    kapp.k14s.io/change-group: "hello-kubernetes/app"
    kapp.k14s.io/change-rule.create-order: "upsert after upserting hello-kubernetes/rbac"
    kapp.k14s.io/change-rule.delete-order: "delete before deleting hello-kubernetes/rbac"
spec:
  serviceAccountName: hello-kubernetes-sa
  fetch:
  - git:
      url: https://github.com/paulbouwer/hello-kubernetes.git
      ref: v1.10.1
      subPath: deploy/helm/hello-kubernetes
  template:
  - helmTemplate:
      valuesFrom:
      - secretRef:
          name: hello-kubernetes-values
  - ytt:
      inline:
        pathsFrom:
        - configMapRef:
            name: hello-kubernetes-overlays
      valuesFrom:
      - secretRef:
          name: hello-kubernetes-values
  deploy:
  - kapp: {}
