apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app
  namespace: hello-kubernetes
spec:
  rules:
  - host: hellokubernetes.az.withtanzu.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hello-kubernetes-hello-kubernetes
            port:
              number: 80
