#@ load("@ytt:overlay", "overlay")

#@overlay/match by=overlay.subset({"metadata": {"labels": { "app.kubernetes.io/name": "hello-kubernetes"}}}),expects="1+"
---
metadata:
  #@overlay/match missing_ok=True
  namespace: hello-kubernetes
---
apiVersion: v1
kind: Namespace
metadata:
  name: hello-kubernetes
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: hello-kubernetes
spec:
  rules:
  - host: hello-kubernetes.az.withtanzu.com
    http:
      paths:
      - pathType: ImplementationSpecific
        path: /
        backend:
          service:
            name: hello-kubernetes-hello-kubernetes
            port:
              number: 80
