apiVersion: v1
kind: Secret
metadata:
  name: spring-on-k8s-values
  namespace: default
  annotations:
    kapp.k14s.io/change-group: "spring-on-k8s/app"
    kapp.k14s.io/change-rule.create-order: "upsert after upserting spring-on-k8s/rbac"
    kapp.k14s.io/change-rule.delete-order: "delete before deleting spring-on-k8s/rbac"
type: Opaque
stringData:
  data.yml: |
    app:
      name: spring-on-k8s-gitops
      conf:
        message: Hello GitOps with Carvel!
    env:
      domain: gitops.dev.corp
