apiVersion: v1
kind: ServiceAccount
metadata:
  name: spring-on-k8s-sa
  namespace: default
  annotations:
    kapp.k14s.io/change-group: "spring-on-k8s/rbac"
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: spring-on-k8s-cluster-role
  annotations:
    kapp.k14s.io/change-group: "spring-on-k8s/rbac"
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: spring-on-k8s-cluster-role-binding
  annotations:
    kapp.k14s.io/change-group: "spring-on-k8s/rbac"
subjects:
- kind: ServiceAccount
  name: spring-on-k8s-sa
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: spring-on-k8s-cluster-role
