apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: spring-on-k8s
  namespace: default
  annotations:
    kapp.k14s.io/change-group: "spring-on-k8s/app"
    kapp.k14s.io/change-rule.create-order: "upsert after upserting spring-on-k8s/rbac"
    kapp.k14s.io/change-rule.delete-order: "delete before deleting spring-on-k8s/rbac"
spec:
  serviceAccountName: spring-on-k8s-sa
  fetch:
  - git:
      url: https://github.com/alexandreroman/k8s-gitops-carvel
      ref: testing
  template:
  - ytt:
      paths:
      - 07-kapp-ytt/bundle/config
      valuesFrom:
      - secretRef:
          name: spring-on-k8s-values
  deploy:
  - kapp: {}
